import React from 'react';

const AnalyticsSchemaNotice: React.FC<{ onDismiss?: () => void }> = ({ onDismiss }) => (
  <div className="bg-yellow-50 border border-yellow-300 text-yellow-800 p-4 rounded-xl my-4 animate-view-enter">
    <div className="flex justify-between items-start">
        <div>
            <p className="font-bold text-lg">⚠️ Aksi Diperlukan: Aktifkan Dasbor Real-time</p>
            <p className="text-sm mt-2 mb-4">
              Dasbor analitik real-time memerlukan tabel <strong>analytics_events</strong> di database Supabase Anda untuk menyimpan data, tetapi tabel tersebut tidak ditemukan.
            </p>
        </div>
        {onDismiss && (
            <button onClick={onDismiss} className="text-yellow-900 font-bold text-xl ml-4 p-1 hover:bg-yellow-100 rounded-full" aria-label="Tutup Notifikasi">&times;</button>
        )}
    </div>
    <div className="text-xs space-y-3 bg-yellow-100 p-3 rounded-md">
      <div>
          <p className="font-bold mb-2">Solusi: Jalankan Kueri SQL Berikut</p>
          <ol className="list-decimal list-inside space-y-1 text-[11px]">
            <li>Di Dashboard Supabase Anda, pergi ke <strong>SQL Editor</strong>.</li>
            <li>Salin dan tempel kueri di bawah ini, lalu klik <strong>"RUN"</strong>.</li>
          </ol>
          <pre className="mt-2 text-[10px] bg-yellow-200 text-yellow-900 p-2 rounded-md overflow-x-auto">
            <code>
{`-- Membuat tabel untuk menyimpan event analitik
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_type text NOT NULL,
    product_id text NULL
);

-- Mengaktifkan Row Level Security (RLS) pada tabel
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Menghapus policy lama jika ada untuk menghindari konflik
DROP POLICY IF EXISTS "Public can insert and admin can read events" ON public.analytics_events;

-- 1. Siapapun (pengunjung toko) dapat memasukkan data baru (INSERT).
-- 2. Hanya pengguna yang terotentikasi (admin) yang dapat membaca data (SELECT).
CREATE POLICY "Public can insert and admin can read events"
ON public.analytics_events FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (true);`}
            </code>
          </pre>
          <p className="text-[11px] mt-2 font-bold">Setelah berhasil, refresh halaman ini. Dasbor real-time Anda akan aktif.</p>
      </div>
    </div>
  </div>
);

export default AnalyticsSchemaNotice;