
import React from 'react';

const CategorySchemaNotice: React.FC<{ onDismiss?: () => void }> = ({ onDismiss }) => (
  <div className="bg-yellow-50 border border-yellow-300 text-yellow-800 p-4 rounded-xl my-4 animate-view-enter">
    <div className="flex justify-between items-start">
        <div>
            <p className="font-bold text-lg">⚠️ Aksi Diperlukan: Buat Tabel Kategori</p>
            <p className="text-sm mt-2 mb-4">
              Fitur kategori memerlukan tabel <strong>categories</strong> di database Supabase Anda, tetapi tabel tersebut tidak ditemukan atau tidak dapat diakses.
            </p>
        </div>
        {onDismiss && (
            <button onClick={onDismiss} className="text-yellow-900 font-bold text-xl ml-4 p-1 hover:bg-yellow-100 rounded-full" aria-label="Tutup Notifikasi">&times;</button>
        )}
    </div>
    <div className="text-xs space-y-3 bg-yellow-100 p-3 rounded-md">
      <div>
          <p className="font-bold mb-2">Solusi: Jalankan Kueri SQL Berikut</p>
          <ol className="list-decimal list-inside space-y-1 text-[11px]">
            <li>Di Dashboard Supabase Anda, pergi ke <strong>SQL Editor</strong>.</li>
            <li>Salin dan tempel kueri di bawah ini, lalu klik <strong>"RUN"</strong>.</li>
          </ol>
          <pre className="mt-2 text-[10px] bg-yellow-200 text-yellow-900 p-2 rounded-md overflow-x-auto">
            <code>
{`-- Membuat tabel untuk menyimpan kategori produk
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Mengaktifkan Row Level Security (RLS) pada tabel
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Menghapus policy lama jika ada untuk menghindari konflik
DROP POLICY IF EXISTS "Public categories are viewable by everyone" ON public.categories;
DROP POLICY IF EXISTS "Admin users can manage categories" ON public.categories;
DROP POLICY IF EXISTS "Public access for admin" ON public.categories;

-- Memberi izin penuh (SELECT, INSERT, UPDATE, DELETE) kepada pengguna anonim (kunci API publik).
-- Ini sesuai untuk panel admin tanpa sistem login pengguna.
CREATE POLICY "Public access for admin"
ON public.categories FOR ALL
USING (true)
WITH CHECK (true);`}
            </code>
          </pre>
          <p className="text-[11px] mt-2 font-bold">Setelah berhasil, refresh halaman ini. Masalah Anda akan teratasi.</p>
      </div>
    </div>
  </div>
);

export default CategorySchemaNotice;
